In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.array([[5378.0, 3270.0, 8750.0, 1989.0, 5961.0, 1560.0],
 [9357.0, 4379.0, 6068.0, 6608.0, np.nan, 4060.0],
 [np.nan, 9102.0, 3358.0, np.nan, 9201.0, 1331.0],
 [2860.0, np.nan, 800.0, 4621.0, 5203.0, 6473.0],
 [9213.0, 9550.0, np.nan, 8094.0, 2622.0, 8032.0],
 [6799.0, 1010.0, 289.0, 2822.0, 1332.0, 6772.0],
 [9329.0, 1426.0, 709.0, 8300.0, np.nan, np.nan],
 [1039.0, 720.0, 5781.0, 9407.0, 9304.0, 2636.0],
 [2316.0, np.nan, 2151.0, 1652.0, 9211.0, 8577.0]])

In [11]:
# find max,min value of each column while ignoring nan values
max_values=np.nanmax(data,axis=0)
min_values=np.nanmin(data,axis=0)

print("Maximum values are:")
print(max_values)

print("Minimum values are:")
print(min_values)


Maximum values are:
[9357. 9550. 8750. 9407. 9304. 8577.]
Minimum values are:
[1039.  720.  289. 1652. 1332. 1331.]


In [13]:
# find indices of min and max value
max_indices=np.nanargmax(data,axis=0)
min_indices=np.nanargmin(data,axis=0)

print("Maximum indices are:")
print(max_indices)

print("Minimum indices are:")
print(min_indices)


Maximum indices are:
[1 4 0 7 7 8]
Minimum indices are:
[7 7 5 8 5 2]


In [17]:
# find the sum,average, std deviation, and variance of each column excluding nan
sum = np.nansum(data, axis=0)
avg = np.nanmean(data, axis=0)
std_deviation = np.nanstd(data, axis=0)
variance = np.nanvar(data, axis=0)

print("Sum of each column excluding nan value is:")
print(sum)

print("Average of each column excluding nan value is:")
print(avg)

print("Standard Deviation of each column excluding nan value is:")
print(std_deviation)

print("Variances of each column excluding nan value is:")
print(variance)

Sum of each column excluding nan value is:
[46291. 29457. 27906. 43493. 42834. 39441.]
Average of each column excluding nan value is:
[5786.375      4208.14285714 3488.25       5436.625      6119.14285714
 4930.125     ]
Standard Deviation of each column excluding nan value is:
[3189.40111688 3454.40002765 2885.07251859 2874.62101578 3052.20788604
 2716.29027524]
Variances of each column excluding nan value is:
[10172279.484375   11932879.55102041  8323643.4375      8263445.984375
  9315972.97959184  7378232.859375  ]


In [ ]:
# fill the nan values of 2nd column with min value of the column
data[:, 1] = np.where(np.isnan(data[:, 1]), np.nanmin(data[:, 1]), data[:, 1])


NameError: name 'np' is not defined

In [ ]:
# Perform zero mean numpy standardization across columns
mean = np.nanmean(data, axis=0)
std = np.nanstd(data, axis=0)
data = (data - mean) / std

# Z-mean Std = data - mean / std
zmean_std = (data - np.nanmean(data)) / np.nanstd(data)
print(zmean_std)

[[-0.08600857 -0.22961478  1.86674696 -1.15780971 -0.00974358 -1.19920612]
 [ 1.16215547  0.09157801  0.93669137  0.44977636         nan -0.2783947 ]
 [        nan  1.45947119 -0.00307397         nan  1.05228883 -1.28355245]
 [-0.87587463 -0.96815546 -0.89012923 -0.24177452 -0.25820672  0.61037249]
 [ 1.11698442  1.58922265         nan  0.96696036 -1.10422698  1.18459049]
 [ 0.3597419  -0.88416456 -1.06733222 -0.86789432 -1.52707321  0.72050153]
 [ 1.15337221 -0.76368106 -0.92168593  1.03865612         nan         nan]
 [-1.44710024 -0.96815546  0.83716641  1.42393384  1.08605097 -0.80288889]
 [-1.04652083 -0.96815546 -0.42163367 -1.27509841  1.0555667   1.38532738]]


In [56]:
# flatten the whole array into a 1d array
flat_data = data.flatten()
print(flat_data)

[-0.12804128 -0.2715791   1.82378431 -1.19933201 -0.05181261 -1.24070871
  1.11952836  0.04946073  0.89417163  0.4074885          nan -0.32033579
         nan  1.4167025  -0.04514618         nan  1.00971404 -1.32501487
 -0.91753119         nan -0.931779   -0.28373305 -0.30015742  0.56800814
  1.07437882  1.54639217         nan  0.92442621 -1.14577479  1.14195269
  0.31749691 -0.92581717 -1.1088976  -0.90955468 -1.56841966  0.67808475
  1.11074928 -0.80539105 -0.96332067  0.99608783         nan         nan
 -1.48848477 -1.00976807  0.79469406  1.38118207  1.0434601  -0.84458021
 -1.08809613         nan -0.46350655 -1.31656485  1.01299035  1.34259399]


In [63]:
# Remove the rows where there is a nan value in the 6th column
remove = data[~np.isnan(data[:, 5])]
print(remove)

[[-0.12804128 -0.2715791   1.82378431 -1.19933201 -0.05181261 -1.24070871]
 [ 1.11952836  0.04946073  0.89417163  0.4074885          nan -0.32033579]
 [        nan  1.4167025  -0.04514618         nan  1.00971404 -1.32501487]
 [-0.91753119 -1.00976807 -0.931779   -0.28373305 -0.30015742  0.56800814]
 [ 1.07437882  1.54639217         nan  0.92442621 -1.14577479  1.14195269]
 [ 0.31749691 -0.92581717 -1.1088976  -0.90955468 -1.56841966  0.67808475]
 [-1.48848477 -1.00976807  0.79469406  1.38118207  1.0434601  -0.84458021]
 [-1.08809613 -1.00976807 -0.46350655 -1.31656485  1.01299035  1.34259399]]
